version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: paolosdb
      POSTGRES_USER: aolop
      #POSTGRES_PASSWORD: notexposedongithub
    ports:
      - "8001:5432"
  paoloserver:
    image: paoloserver:posty
    ports:
      - "5000:5000"
